<a href="https://colab.research.google.com/github/Madhavasudharsun/sales_question/blob/main/sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
sales = pd.read_csv("/content/sales_data_set.csv")
stores = pd.read_csv("/content/stores_data_set.csv")
features = pd.read_csv("/content/Features_data_set.csv")

In [4]:
sales.columns,stores.columns,features.columns

(Index(['Store', 'Dept', 'Date', 'Weekly_Sales', 'IsHoliday'], dtype='object'),
 Index(['Store', 'Type', 'Size'], dtype='object'),
 Index(['Store', 'Date', 'Temperature', 'Fuel_Price', 'MarkDown1', 'MarkDown2',
        'MarkDown3', 'MarkDown4', 'MarkDown5', 'CPI', 'Unemployment',
        'IsHoliday'],
       dtype='object'))

In [5]:
sales.info(),stores.info(),features.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421570 entries, 0 to 421569
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   Store         421570 non-null  int64
 1   Dept          421570 non-null  int64
 2   Date          421570 non-null  object
 3   Weekly_Sales  421570 non-null  float64
 4   IsHoliday     421570 non-null  bool
dtypes: bool(1), float64(1), int64(2), object(1)
memory usage: 13.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45 entries, 0 to 44
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Store   45 non-null     int64
 1   Type    45 non-null     object
 2   Size    45 non-null     int64
dtypes: int64(2), object(1)
memory usage: 1.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Store         8190 non-null   int64
 1   Date          8190 non-null   object
 2   Temperature   8190 non-null   float64
 3   Fuel_Price    8190 non-null   float64
 4   MarkDown1     4032 non-null   float64
 5   MarkDown2     2921 non-null   float64
 6   MarkDown3     3613 non-null   float64
 7   MarkDown4     3464 non-null   float64
 8   MarkDown5     4050 non-null   float64
 9   CPI           7605 non-null   float64
 10  Unemployment  7605 non-null   float64
 11  IsHoliday     8190 non-null   bool
dtypes: bool(1), float64(9), int64(1), object(1)
memory usage: 712.0+ KB

(None, None, None)

In [6]:
sales['Date'] = pd.to_datetime(sales['Date'], format='%d/%m/%Y')
features['Date'] = pd.to_datetime(features['Date'], format='%d/%m/%Y')

In [8]:
df

        Store  Dept       Date  Weekly_Sales  IsHoliday Type    Size
0           1     1 2010-02-05      24924.50      False    A  151315
1           1     1 2010-02-12      46039.49       True    A  151315
2           1     1 2010-02-19      41595.55      False    A  151315
3           1     1 2010-02-26      19403.54      False    A  151315
4           1     1 2010-03-05      21827.90      False    A  151315
...       ...   ...        ...           ...        ...  ...     ...
421565     45    98 2012-09-28        508.37      False    B  118221
421566     45    98 2012-10-05        628.10      False    B  118221
421567     45    98 2012-10-12       1061.02      False    B  118221
421568     45    98 2012-10-19        760.01      False    B  118221
421569     45    98 2012-10-26       1076.80      False    B  118221

[421570 rows x 7 columns]


** Identify average customer visit in the type B store in April Months***

In [7]:
df = pd.merge(sales, stores, on='Store')

# Filter for Type B stores
type_b_stores = df[df['Type'] == 'B']

# Filter for sales data in April
april_data = type_b_stores[type_b_stores['Date'].dt.month == 4]

# Calculate average weekly sales (assuming weekly sales represent customer visits)
average_customer_visit = april_data['Weekly_Sales'].mean()

print(f'Average customer visit in Type B stores for April: {average_customer_visit}')

Average customer visit in Type B stores for April: 11924.820053101768